name: carenow2
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.18.1

  # Firebase dependencies
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.1
  cloud_firestore: ^4.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/logo.png
    - lib/assets/images/care1.png
    - lib/assets/images/user1.png


